### ISSUE TITLE
pip install btzen - error code 1, tmp file does not exist

### ISSUE THREAD

**Issue by ILoveMuffins** [wrobell/btzen#1]
I tried everything - upgrade pip, upgrade setuptools, install ez_setup, and still after:
`$ sudo pip3.6 install btzen`
the error is:

>     gcc -pthread -shared build/temp.linux-armv7l-3.6/btzen/_btzen.o -lsystemd -o build/lib.linux-armv7l-3.6/btzen/_btzen.cpython-36m-arm-linux-gnueabihf.so
>     running build_scripts
>     creating build/scripts-3.6
>     error: file '/tmp/pip-build-jslan4pf/btzen/bin/btzen' does not exist
> 
>     ----------------------------------------
> Command "/usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jslan4pf/btzen/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-uxjebp5y-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-jslan4pf/btzen/

I'm trying to install btzen at raspbian stretch, maybe this is the case?

**Comment by wrobell** [comment]
Fixed in commit https://github.com/wrobell/btzen/commit/0214e39144c1f474c833a1c7779f1089473313ae. Please try again with the same command used by you above.

**Comment by ILoveMuffins** [comment]
Thanks a million! Working :+1:
