### ISSUE TITLE
multiple sensors issue

### ISSUE THREAD

**Issue by ILoveMuffins** [wrobell/btzen#2]
I'm having an issues while trying to connect to multiple sensors.
Most of the time, data is read from only one cc2650 SensorTag.

Sometimes it's event Segmentation fault:

AttributeError: 'tuple' object has no attribute 'set_result'
Exception ignored in: 'btzen._btzen.task_cb_write'
AttributeError: 'tuple' object has no attribute 'set_result'
Segmentation fault

I tried to modify your script btzen-sensor-tag to read from multiple sensors, but I'm still having issues, maybe it's bluetooth problem. Here's the script:
[btzen-sensor-tag.txt](https://github.com/wrobell/btzen/files/1716288/btzen-sensor-tag.txt)

**Comment by wrobell** [comment]
Multiple Sensor Tag devices should work indeed.

Can I ask you to check if the script works for each single device? Could you also create a much simpler script?

**Comment by ILoveMuffins** [comment]
It was working for a while, so it actually may be problem with my devices.
Most of them have very low rate of successful connections, when I test them independently.
Only one works pretty well.

[btzen-sensor-tag.txt](https://github.com/wrobell/btzen/files/1716917/btzen-sensor-tag.txt)
Here's better script, just pass device addresses to _addresses_ list. It shoud work now.
I'll check it with new devices sometime in the future.

Thanks for your help!

**Comment by wrobell** [comment]
I experienced connectivity issues (i.e. disconnecting in the middle of transmission) in two cases

1. Older version of firmware.
2. Low battery.

**Comment by ILoveMuffins** [comment]
Yeah, after taking research I found out that I've got older version of firmware.
Sensors are powered with the cable, so the second one is not my case.
