### ISSUE TITLE
Wake-on-motion

### ISSUE THREAD

**Issue by binderth** [wrobell/btzen#3]
Hi there,

thanks for this cool library. I'd like to use my CC2650 sensors only while they're in Motion. I only need information at the time there is movement from the sensor. 
I'm unsure how to achieve this, are there any examples on this around?

Thanks for help!
Thomas.

**Comment by wrobell** [comment]
Please see `scripts/btzen-sensor-tag` script.

In general, just create accelerometer instance and read the data
```
sensor = btzen.Accelerometer(<mac address>, notifying=True)

# in a coroutine
while True:
    data = await sensor.read()
```

**Comment by binderth** [comment]
wow! That was fast! ;)

Yes, I do that now and it works - as long as the battery lasts.... Doing this kind of heavy pulling, the battery is empty after two days or so. 
So my thinking was, it should be possible to have the sensortag go to deep sleep and only send information, if theres motion.

**Comment by wrobell** [comment]
The `await sensor.read()` should return only when you move the sensor. The sensor will provide few more readings (10 if I remember well) and then stop. Once it is stopped the read call should hang until next sensor move.

Last time I tested it, the power usage was dropping down quite significantly when sensor stopped providing data (measure with an appropriate multimeter).

**Comment by binderth** [comment]
Thanks again for your fast answer! I'll double check, if the sensor.read() is in my script, when I'm home.

Cheers,
Thomas.
