### ISSUE TITLE
Handling aid

### ISSUE THREAD

**Issue by jbsky** [wrobell/btzen#5]
Hello,

Since I'm having a little trouble, I'm taking the liberty of soliciting you via Github.

I did a test on 2 "detect and connect" scripts, I left the command lines.

Can you just help me debugging afterwards, I promise I won't bother you anymore :D.

root@thermometre:~/btzen/scripts# python3.8 btzen-detect
Traceback (most recent call last):
  File "btzen-detect", line 33, in <module>
    from btzen.bus import BUS
ImportError: cannot import name 'BUS' from 'btzen.bus' (/usr/local/lib/python3.8/site-packages/btzen/bus.py)

INFO:btzen.cm:connect device A4:C1:38:FD:1C:8D via controller /org/bluez/hci0, address type public
INFO:btzen.cm:connection for A4:C1:38:FD:1C:8D failed: Method "ConnectDevice" with signature "a{sv}" on interface "org.bluez.Adapter1" doesn't exist

root@thermometre:~/btzen/scripts# python3.8 btzen-connect devices A4:C1:38:FD:1C:8D
INFO:btzen._cm:register reconnection for service: devices
INFO:btzen.cm:connect device A4:C1:38:FD:1C:8D via controller /org/bluez/hci0, address type public
INFO:btzen.cm:connection for A4:C1:38:FD:1C:8D failed: Method "ConnectDevice" with signature "a{sv}" on interface "org.bluez.Adapter1" doesn't exist
, sleep for 1s
INFO:btzen.cm:connect device A4:C1:38:FD:1C:8D via controller /org/bluez/hci0, address type public
INFO:btzen.cm:connection for A4:C1:38:FD:1C:8D failed: Method "ConnectDevice" with signature "a{sv}" on interface "org.bluez.Adapter1" doesn't exist
, sleep for 1s

**Comment by jbsky** [comment]
Well, definitely, I can't read,
option -E is missing
So, python3.8 btzen-connect devices A4:C1:38:FD:1C:8D works better.

However, that still doesn't explain the mistake: root@thermometre:~/btzen/scripts# python3.8 btzen-detect
Traceback (most recent call last):
File "btzen-detect", line 33, in
from btzen.bus import BUS
ImportError: cannot import name 'BUS' from 'btzen.bus' (/usr/local/lib/python3.8/site-packages/btzen/bus.py)

**Comment by wrobell** [comment]
The `btzen-detect` script is out of date. I need to fix it indeed.

If I understand well, `btzen-connect` works?

**Comment by jbsky** [comment]
To be clear, I'm trying to capture data from a mijia v2 temperature/humidity sensor (LYWSD03MMC).

With hcitool, I can connect to the device very well and see that the notifications arrive correctly.

To get the battery level, the UUID is: 00002a19-0000-1000-8000-00805f9b34fb

Normally, it should work, but unfortunately, I have this answer:

/home/webmaster/PycharmProjects/btconnect/bin/python3.8 /home/webmaster/PycharmProjects/btconnect/btzen-connect device A4:C1:38:22:12:A0 service 00002a19-0000-1000-8000-00805f9b34fb
INFO:btzen._cm:register reconnection for service: device
INFO:btzen.cm:connect device A4:C1:38:22:12:A0 via controller /org/bluez/hci0, address type public
INFO:btzen.cm:connect device service via controller /org/bluez/hci0, address type public
INFO:btzen.cm:connection for service failed: Invalid arguments in method call, sleep for 1s
INFO:btzen.device:device A4:C1:38:22:12:A0/Device disabled
INFO:btzen.device:device A4:C1:38:22:12:A0/Device closed
INFO:btzen.device:device service/Device disabled
INFO:btzen.device:device service/Device closed
INFO:btzen.device:device 00002a19-0000-1000-8000-00805f9b34fb/Device disabled
INFO:btzen.device:device 00002a19-0000-1000-8000-00805f9b34fb/Device closed
WARNING:btzen.cm:error when disconnecting A4:C1:38:22:12:A0: Call failed - disconnect device: Invalid request descriptor (-53)
WARNING:btzen.cm:error when disconnecting service: Call failed - disconnect device: Invalid request descriptor (-53)
WARNING:btzen.cm:error when disconnecting 00002a19-0000-1000-8000-00805f9b34fb: Call failed - disconnect device: Invalid argument (-22)
INFO:btzen.cm:connection manager closed
Traceback (most recent call last):
  File "/home/webmaster/PycharmProjects/btconnect/btzen-connect", line 59, in <module>
    loop.run_until_complete(manager)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 684, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/webmaster/PycharmProjects/btconnect/lib/python3.8/site-packages/btzen/cm.py", line 135, in __await__
    yield from asyncio.gather(*tasks).__await__()
  File "/home/webmaster/PycharmProjects/btconnect/lib/python3.8/site-packages/btzen/cm.py", line 151, in _reconnect
    bus._dev_property_start(mac, 'ServicesResolved')
  File "/home/webmaster/PycharmProjects/btconnect/lib/python3.8/site-packages/btzen/bus.py", line 93, in _dev_property_start
    self._notifications.start(path, iface, name)
  File "/home/webmaster/PycharmProjects/btconnect/lib/python3.8/site-packages/btzen/bus.py", line 131, in start
    data = _btzen.bt_property_monitor_start(bus, path, iface)
  File "btzen/_btzen.pyx", line 294, in btzen._btzen.bt_property_monitor_start
  File "btzen/_sd_bus.pyx", line 66, in btzen._sd_bus.check_call
btzen.error.CallError: Call failed - bus match rule: Invalid argument (-22)

If I leave out the service argument, personally, I don't see the point:

/home/webmaster/PycharmProjects/btconnect/bin/python3.8 /home/webmaster/PycharmProjects/btconnect/btzen-connect device A4:C1:38:22:12:A0
INFO:btzen._cm:register reconnection for service: device
INFO:btzen.cm:connect device A4:C1:38:22:12:A0 via controller /org/bluez/hci0, address type public
INFO:btzen.cm:device A4:C1:38:22:12:A0 waiting for services resolved status change
INFO:btzen.cm:device A4:C1:38:22:12:A0 services resolved: False
INFO:btzen.device:device A4:C1:38:22:12:A0/Device disabled
INFO:btzen.cm:device A4:C1:38:22:12:A0 waiting for services resolved status change

**Comment by wrobell** [comment]
The command should be

```
btzen-connect <service-uuid> A4:C1:38:22:12:A0
```
where `<service-uuid>` can be temperature service UUID of a sensor.

`00002a19-0000-1000-8000-00805f9b34fb` is battery level characteristics UUID, so it will not work.

For example, for Sensor Tag, the temperature service UUID is `'f000aa00-0451-4000-b000-000000000000` and temperature characteristics UUID is `'f000aa01-0451-4000-b000-000000000000` (`aa00` vs `aa01`). You can figure out sensor's UUIDs by looking at D-Bus data with d-feet or similar application.

Please note, that the script is just for testing device connection/reconnection, i.e.
- start the script
- go out of range or switch of your sensor
- bring your sensor back into range or switch it on
- see that sensor is reconnected

**Comment by jbsky** [comment]
Ok, if I understand the btconnect scenario correctly, it simply allows a connection, and a reconnection in case of signal loss, so the uUID is useless.

Let's move on to the implementation part:

webmaster@Cross:~/btzen/scrippython3.8 btzen-connect 00002a19-0000-1000-8000-00805f9b34fb A4:C1:38:A6:97:65
INFO:btzen._cm:register reconnection for service: 00002a19-0000-1000-8000-00805f9b34fb
INFO:btzen.cm:connect device A4:C1:38:A6:97:65 via controller /org/bluez/hci0, address type public
INFO:btzen.cm:device A4:C1:38:A6:97:65 waiting for services resolved status change
INFO:btzen.cm:device A4:C1:38:A6:97:65 services resolved: True
INFO:btzen.cm:enabling device A4:C1:38:A6:97:65
INFO:btzen.cm:device A4:C1:38:A6:97:65 waiting for services resolved status change

So, now it's running, it's well connected, is that ok? If yes, I'm closing the issue.

On the other hand, for the sensor and battery part, indeed, SensorTag is not adapted to this small sensor. For example, the notifications have this id: ebe0ccc1-7a0a-4b0c-8a1a-6ff2997da3a6

INFO:btzen._cm:register reconnection for service: 0000180f-0000-1000-8000-00805f9b34fb
INFO:btzen._cm:register reconnection for service: 0000ffe0-0000-1000-8000-00805f9b34fb
INFO:btzen._cm:register reconnection for service: f000aa00-0451-4000-b000-000000000000
INFO:btzen._cm:register reconnection for service: f000aa20-0451-4000-b000-000000000000
INFO:btzen._cm:register reconnection for service: f000aa40-0451-4000-b000-000000000000
INFO:btzen._cm:register reconnection for service: f000aa70-0451-4000-b000-000000000000
INFO:btzen._cm:register reconnection for service: f000aa80-0451-4000-b000-000000000000
INFO:btzen.cm:connect device A4:C1:38:A6:97:65 via controller /org/bluez/hci0, address type public
INFO:btzen.cm:device A4:C1:38:A6:97:65 waiting for services resolved status change
INFO:btzen.cm:device A4:C1:38:A6:97:65 services resolved: True
INFO:btzen.cm:enabling device A4:C1:38:A6:97:65
INFO:btzen.device:enabling device: A4:C1:38:A6:97:65/Temperature
INFO:btzen.cm:enabling device A4:C1:38:A6:97:65 failed, seems to be not connected
ERROR:btzen.cm:error when enabling A4:C1:38:A6:97:65
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/btzen/cm.py", line 183, in _restart
    await enable()
  File "/usr/local/lib/python3.8/site-packages/btzen/cm.py", line 240, in _enable
    await t
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.8/site-packages/btzen/device.py", line 246, in enable
    await self._configure()
  File "/usr/local/lib/python3.8/site-packages/btzen/sensortag.py", line 61, in _configure
    await super()._configure()
  File "/usr/local/lib/python3.8/site-packages/btzen/device.py", line 333, in _configure
    await self._write(self._path_conf, config_on)
  File "/usr/local/lib/python3.8/site-packages/btzen/device.py", line 352, in _write
    await _btzen.bt_write(self._bus.system_bus, path, data)
  File "btzen/_btzen.pyx", line 167, in bt_write
AssertionError
INFO:btzen.device:device A4:C1:38:A6:97:65/Temperature disabled
INFO:btzen.device:device A4:C1:38:A6:97:65/Light disabled
WARNING:btzen.device:cannot stop notifications: 
INFO:btzen.device:device A4:C1:38:A6:97:65/Accelerometer disabled
WARNING:btzen.device:cannot stop notifications: 
INFO:btzen.device:device A4:C1:38:A6:97:65/Button disabled
INFO:btzen.device:device A4:C1:38:A6:97:65/Pressure disabled
INFO:btzen.device:device A4:C1:38:A6:97:65/Humidity disabled
WARNING:btzen.device:cannot stop notifications: ('/org/bluez/hci0/dev_A4_C1_38_A6_97_65', 'org.bluez.Battery1')
INFO:btzen.device:device A4:C1:38:A6:97:65/BatteryLevel disabled
INFO:btzen.cm:device A4:C1:38:A6:97:65 waiting for services resolved status change

**Comment by jbsky** [comment]
Okay, I get it, here you're talking about service obtainable through this command:

[A4:C1:38:A6:97:65][LE]> primary
attr handle: 0x0001, end grp handle: 0x0007 uuid: 00001800-0000-1000-8000-00805f9b34fb
attr handle: 0x0008, end grp handle: 0x000b uuid: 00001801-0000-1000-8000-00805f9b34fb
attr handle: 0x000c, end grp handle: 0x0018 uuid: 0000180a-0000-1000-8000-00805f9b34fb
attr handle: 0x0019, end grp handle: 0x001c uuid: 0000180f-0000-1000-8000-00805f9b34fb
attr handle: 0x001d, end grp handle: 0x0020 uuid: 00010203-0405-0607-0809-0a0b0c0d1912
attr handle: 0x0021, end grp handle: 0x004b uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6
attr handle: 0x004c, end grp handle: 0x005f uuid: 0000fe95-0000-1000-8000-00805f9b34fb
attr handle: 0x0060, end grp handle: 0x0068 uuid: 00000100-0065-6c62-2e74-6f696d2e696d

So I'm typing the following command, 
I got a service to True, okay!

webmaster@Cross:~/btzen/scripts$ python3.8 btzen-connect 00001800-0000-1000-8000-00805f9b34fb A4:C1:38:A6:97:65
INFO:btzen._cm:register reconnection for service: 00001800-0000-1000-8000-00805f9b34fb
INFO:btzen.cm:connect device A4:C1:38:A6:97:65 via controller /org/bluez/hci0, address type public
INFO:btzen.cm:device A4:C1:38:A6:97:65 waiting for services resolved status change
INFO:btzen.cm:device A4:C1:38:A6:97:65 services resolved: **True**
INFO:btzen.cm:enabling device A4:C1:38:A6:97:65
INFO:btzen.cm:device A4:C1:38:A6:97:65 waiting for services resolved status change

Sorry if I find out about BLE too.

Can I subscribe to notifications with btzen?

If I connect with gatttool, I gave this notification :
Notification handle = 0x0036 value: **7e 09 40 f4 0a**

**Comment by wrobell** [comment]
I am using `bt-connect` script to test connection manager. There is no other functionality.

Sensor Tag is device sold by Texas Instruments. The device provides multiple sensors but they are not compliant with Bluetooth services/characteristics specification (see below for links).

Therefore implementation for Sensor Tag sensors is in `btzen.sensortag` module. The same for Thingy:52 (`btzen.thingy52`). I am just trying my best to implement the same interface for them.

I suspect the sensor you are using will need its own implementation as well. Just look how it is done for Thingy:52 and Sensor Tag. Sensor Tag supports both reading data on demand and notifications. Thingy:52 supports notifications only.

See also list of Bluetooth services and characteristics.

- https://www.bluetooth.com/specifications/gatt/services/
- https://www.bluetooth.com/specifications/gatt/characteristics/
